"""update repository snapshots

Revision ID: 517e4ad2ac44
Revises: 78ab43bbabb6
Create Date: 2025-12-28 15:17:30.449127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517e4ad2ac44'
down_revision: Union[str, Sequence[str], None] = '78ab43bbabb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('has_projects', sa.Boolean(), nullable=False))
    op.add_column('repositories', sa.Column('has_downloads', sa.Boolean(), nullable=False))
    op.add_column('repositories', sa.Column('has_pages', sa.Boolean(), nullable=False))
    op.add_column('repositories', sa.Column('has_discussions', sa.Boolean(), nullable=False))
    op.add_column('repositories_snapshots', sa.Column('subscribers_count', sa.Integer(), nullable=False))
    op.drop_column('repositories_snapshots', 'watchers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories_snapshots', sa.Column('watchers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('repositories_snapshots', 'subscribers_count')
    op.drop_column('repositories', 'has_discussions')
    op.drop_column('repositories', 'has_pages')
    op.drop_column('repositories', 'has_downloads')
    op.drop_column('repositories', 'has_projects')
    # ### end Alembic commands ###
