"""Initial revision

Revision ID: 78ab43bbabb6
Revises: 
Create Date: 2025-12-23 15:53:27.254830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ab43bbabb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('login_name', sa.String(length=50), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('login_name')
    )
    op.create_index('ix_owner_created', 'owners', ['created_at'], unique=False)
    op.create_index('ix_owner_type', 'owners', ['owner_type'], unique=False)
    op.create_table('owners_snapshots',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('public_repos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'collected_at')
    )
    op.create_index('ix_owner_snapshots_collected', 'owners_snapshots', ['owner_id', 'collected_at'], unique=False)
    op.create_index('ix_owner_snapshots_date', 'owners_snapshots', ['collected_at'], unique=False)
    op.create_table('repositories',
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.Column('repo_language', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('size_kb', sa.Integer(), nullable=False),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('has_issues', sa.Boolean(), nullable=False),
    sa.Column('has_wiki', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('repo_id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index('ix_repo_created', 'repositories', ['created_at'], unique=False)
    op.create_index('ix_repo_language', 'repositories', ['repo_language'], unique=False)
    op.create_index('ix_repo_owner', 'repositories', ['owner_id'], unique=False)
    op.create_table('repositories_snapshots',
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('watchers', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('size_kb', sa.Integer(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repo_id', 'collected_at')
    )
    op.create_index('ix_repo_snapshots_collected', 'repositories_snapshots', ['collected_at'], unique=False)
    op.create_index('ix_repo_snapshots_forks', 'repositories_snapshots', ['forks'], unique=False)
    op.create_index('ix_repo_snapshots_repo_collected', 'repositories_snapshots', ['repo_id', 'collected_at'], unique=False)
    op.create_index('ix_repo_snapshots_stars', 'repositories_snapshots', ['stars'], unique=False)
    op.create_table('tracked_repositories',
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('tracking_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repo_id')
    )
    op.create_index('ix_tracked_started', 'tracked_repositories', ['tracking_started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracked_started', table_name='tracked_repositories')
    op.drop_table('tracked_repositories')
    op.drop_index('ix_repo_snapshots_stars', table_name='repositories_snapshots')
    op.drop_index('ix_repo_snapshots_repo_collected', table_name='repositories_snapshots')
    op.drop_index('ix_repo_snapshots_forks', table_name='repositories_snapshots')
    op.drop_index('ix_repo_snapshots_collected', table_name='repositories_snapshots')
    op.drop_table('repositories_snapshots')
    op.drop_index('ix_repo_owner', table_name='repositories')
    op.drop_index('ix_repo_language', table_name='repositories')
    op.drop_index('ix_repo_created', table_name='repositories')
    op.drop_table('repositories')
    op.drop_index('ix_owner_snapshots_date', table_name='owners_snapshots')
    op.drop_index('ix_owner_snapshots_collected', table_name='owners_snapshots')
    op.drop_table('owners_snapshots')
    op.drop_index('ix_owner_type', table_name='owners')
    op.drop_index('ix_owner_created', table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
